### PR TITLE
test cumulttfrom in fortran

### PR DESCRIPTION
**Pull request by cyrillemidingoyi**
@pradal 
Hi Christophe,
please, can you check this file. it is a test of the difference of  thermal time cumulated at the currentdate and a development growth stage coded in fortran. When the file is built, it generated an error: "undefined reference to `findloc_'"
I spent more time on this but I had no solution.
Thank

### CODE REVIEW

**Comment by pradal** [comment]
FINDLOC has been implemented only in Fortran 2008 (gfortran 9)

**Comment by cyrillemidingoyi** [comment]
oh. I would just like to retrieve the index of an element of vector.
In python, java and C# it is more expressive than C++.

**Comment by pradal** [comment]
Fortran you mean?

**Comment by cyrillemidingoyi** [comment]
c++ also. You can check it in src/cpp/CumulttFrom.cpp

**Pull request merged**
